/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Receptionist__factory } from "./Receptionist__factory";
export { Rooms__factory } from "./Rooms__factory";
